//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio_2.BancoEconomicoSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://bancoeconomico.org/")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        private double MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bancoeconomico.org/", ConfigurationName="BancoEconomicoSoap.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres http://bancoeconomico.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://bancoeconomico.org/consultarSaldo", ReplyAction="*")]
        Comercio_2.BancoEconomicoSoap.consultarSaldoResponse consultarSaldo(Comercio_2.BancoEconomicoSoap.consultarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bancoeconomico.org/consultarSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<Comercio_2.BancoEconomicoSoap.consultarSaldoResponse> consultarSaldoAsync(Comercio_2.BancoEconomicoSoap.consultarSaldoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres http://bancoeconomico.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://bancoeconomico.org/historial", ReplyAction="*")]
        Comercio_2.BancoEconomicoSoap.historialResponse historial(Comercio_2.BancoEconomicoSoap.historialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bancoeconomico.org/historial", ReplyAction="*")]
        System.Threading.Tasks.Task<Comercio_2.BancoEconomicoSoap.historialResponse> historialAsync(Comercio_2.BancoEconomicoSoap.historialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarSaldo", Namespace="http://bancoeconomico.org/", Order=0)]
        public Comercio_2.BancoEconomicoSoap.consultarSaldoRequestBody Body;
        
        public consultarSaldoRequest() {
        }
        
        public consultarSaldoRequest(Comercio_2.BancoEconomicoSoap.consultarSaldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bancoeconomico.org/")]
    public partial class consultarSaldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public consultarSaldoRequestBody() {
        }
        
        public consultarSaldoRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarSaldoResponse", Namespace="http://bancoeconomico.org/", Order=0)]
        public Comercio_2.BancoEconomicoSoap.consultarSaldoResponseBody Body;
        
        public consultarSaldoResponse() {
        }
        
        public consultarSaldoResponse(Comercio_2.BancoEconomicoSoap.consultarSaldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bancoeconomico.org/")]
    public partial class consultarSaldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double consultarSaldoResult;
        
        public consultarSaldoResponseBody() {
        }
        
        public consultarSaldoResponseBody(double consultarSaldoResult) {
            this.consultarSaldoResult = consultarSaldoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class historialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="historial", Namespace="http://bancoeconomico.org/", Order=0)]
        public Comercio_2.BancoEconomicoSoap.historialRequestBody Body;
        
        public historialRequest() {
        }
        
        public historialRequest(Comercio_2.BancoEconomicoSoap.historialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bancoeconomico.org/")]
    public partial class historialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public historialRequestBody() {
        }
        
        public historialRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class historialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="historialResponse", Namespace="http://bancoeconomico.org/", Order=0)]
        public Comercio_2.BancoEconomicoSoap.historialResponseBody Body;
        
        public historialResponse() {
        }
        
        public historialResponse(Comercio_2.BancoEconomicoSoap.historialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bancoeconomico.org/")]
    public partial class historialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Comercio_2.BancoEconomicoSoap.Movimiento[] historialResult;
        
        public historialResponseBody() {
        }
        
        public historialResponseBody(Comercio_2.BancoEconomicoSoap.Movimiento[] historialResult) {
            this.historialResult = historialResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Comercio_2.BancoEconomicoSoap.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Comercio_2.BancoEconomicoSoap.WebService1Soap>, Comercio_2.BancoEconomicoSoap.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comercio_2.BancoEconomicoSoap.consultarSaldoResponse Comercio_2.BancoEconomicoSoap.WebService1Soap.consultarSaldo(Comercio_2.BancoEconomicoSoap.consultarSaldoRequest request) {
            return base.Channel.consultarSaldo(request);
        }
        
        public double consultarSaldo(string cuenta) {
            Comercio_2.BancoEconomicoSoap.consultarSaldoRequest inValue = new Comercio_2.BancoEconomicoSoap.consultarSaldoRequest();
            inValue.Body = new Comercio_2.BancoEconomicoSoap.consultarSaldoRequestBody();
            inValue.Body.cuenta = cuenta;
            Comercio_2.BancoEconomicoSoap.consultarSaldoResponse retVal = ((Comercio_2.BancoEconomicoSoap.WebService1Soap)(this)).consultarSaldo(inValue);
            return retVal.Body.consultarSaldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comercio_2.BancoEconomicoSoap.consultarSaldoResponse> Comercio_2.BancoEconomicoSoap.WebService1Soap.consultarSaldoAsync(Comercio_2.BancoEconomicoSoap.consultarSaldoRequest request) {
            return base.Channel.consultarSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comercio_2.BancoEconomicoSoap.consultarSaldoResponse> consultarSaldoAsync(string cuenta) {
            Comercio_2.BancoEconomicoSoap.consultarSaldoRequest inValue = new Comercio_2.BancoEconomicoSoap.consultarSaldoRequest();
            inValue.Body = new Comercio_2.BancoEconomicoSoap.consultarSaldoRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Comercio_2.BancoEconomicoSoap.WebService1Soap)(this)).consultarSaldoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comercio_2.BancoEconomicoSoap.historialResponse Comercio_2.BancoEconomicoSoap.WebService1Soap.historial(Comercio_2.BancoEconomicoSoap.historialRequest request) {
            return base.Channel.historial(request);
        }
        
        public Comercio_2.BancoEconomicoSoap.Movimiento[] historial(string cuenta) {
            Comercio_2.BancoEconomicoSoap.historialRequest inValue = new Comercio_2.BancoEconomicoSoap.historialRequest();
            inValue.Body = new Comercio_2.BancoEconomicoSoap.historialRequestBody();
            inValue.Body.cuenta = cuenta;
            Comercio_2.BancoEconomicoSoap.historialResponse retVal = ((Comercio_2.BancoEconomicoSoap.WebService1Soap)(this)).historial(inValue);
            return retVal.Body.historialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comercio_2.BancoEconomicoSoap.historialResponse> Comercio_2.BancoEconomicoSoap.WebService1Soap.historialAsync(Comercio_2.BancoEconomicoSoap.historialRequest request) {
            return base.Channel.historialAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comercio_2.BancoEconomicoSoap.historialResponse> historialAsync(string cuenta) {
            Comercio_2.BancoEconomicoSoap.historialRequest inValue = new Comercio_2.BancoEconomicoSoap.historialRequest();
            inValue.Body = new Comercio_2.BancoEconomicoSoap.historialRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((Comercio_2.BancoEconomicoSoap.WebService1Soap)(this)).historialAsync(inValue);
        }
    }
}
