//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteCotizacion.ReferenciaLaboratorio {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioCotizacionSoap", Namespace="http://tempuri.org/CotizacionSOAP/")]
    public partial class ServicioCotizacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback obtenerCotizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarCotizacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioCotizacion() {
            this.Url = global::ClienteCotizacion.Properties.Settings.Default.ClienteCotizacion_ReferenciaLaboratorio_ServicioCotizacion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event obtenerCotizacionCompletedEventHandler obtenerCotizacionCompleted;
        
        /// <remarks/>
        public event registrarCotizacionCompletedEventHandler registrarCotizacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CotizacionSOAP/obtenerCotizacion", RequestNamespace="http://tempuri.org/CotizacionSOAP/", ResponseNamespace="http://tempuri.org/CotizacionSOAP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string obtenerCotizacion(string fecha) {
            object[] results = this.Invoke("obtenerCotizacion", new object[] {
                        fecha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerCotizacionAsync(string fecha) {
            this.obtenerCotizacionAsync(fecha, null);
        }
        
        /// <remarks/>
        public void obtenerCotizacionAsync(string fecha, object userState) {
            if ((this.obtenerCotizacionOperationCompleted == null)) {
                this.obtenerCotizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerCotizacionOperationCompleted);
            }
            this.InvokeAsync("obtenerCotizacion", new object[] {
                        fecha}, this.obtenerCotizacionOperationCompleted, userState);
        }
        
        private void OnobtenerCotizacionOperationCompleted(object arg) {
            if ((this.obtenerCotizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerCotizacionCompleted(this, new obtenerCotizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CotizacionSOAP/registrarCotizacion", RequestNamespace="http://tempuri.org/CotizacionSOAP/", ResponseNamespace="http://tempuri.org/CotizacionSOAP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string registrarCotizacion(string fecha, decimal monto) {
            object[] results = this.Invoke("registrarCotizacion", new object[] {
                        fecha,
                        monto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registrarCotizacionAsync(string fecha, decimal monto) {
            this.registrarCotizacionAsync(fecha, monto, null);
        }
        
        /// <remarks/>
        public void registrarCotizacionAsync(string fecha, decimal monto, object userState) {
            if ((this.registrarCotizacionOperationCompleted == null)) {
                this.registrarCotizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarCotizacionOperationCompleted);
            }
            this.InvokeAsync("registrarCotizacion", new object[] {
                        fecha,
                        monto}, this.registrarCotizacionOperationCompleted, userState);
        }
        
        private void OnregistrarCotizacionOperationCompleted(object arg) {
            if ((this.registrarCotizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarCotizacionCompleted(this, new registrarCotizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void obtenerCotizacionCompletedEventHandler(object sender, obtenerCotizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerCotizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerCotizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void registrarCotizacionCompletedEventHandler(object sender, registrarCotizacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarCotizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarCotizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591